version: '3'
services:
  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: printerdrive
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: printerdrive
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork: